### PR TITLE
Require Node.js 6 and add 100% code coverage

### PR DESCRIPTION
**Pull request by coreyfarrell**
This gives 100% test coverage on all platforms.  Let me know if you dislike what I've done in `test/eacces.js`.  I could setup real EACCES testing for Linux when run as non-root with the path `/root/private`, but I could not find a path that would provide this test coverage for Windows or Mac.

### CODE REVIEW

**Comment by sindresorhus** [comment]
> Let me know if you dislike what I've done in `test/eacces.js`.

It's good.

**Comment by sindresorhus** [comment]
I'm gonna wait a month before publishing as I want to drop Node.js 6 too so I can drop `pify`.

**Comment by coreyfarrell** [comment]
> I'm gonna wait a month before publishing as I want to drop Node.js 6 too so I can drop `pify`.

I assume you'll replace with `util.promisify` and use async/await?  I can help update some of your modules to node.js 8 by following `npm ls pify` on a production install of `nyc` (we'll be upgrading to node.js 8 as well).

**Comment by sindresorhus** [comment]
Yes. And help more than welcome.

**Pull request merged**
